### ISSUE TITLE
BOT cannot be moved, do you need to create it?

### ISSUE THREAD

**Issue by LoveMiku233** [SquarerFive/bf3-bots#17]
`AttributeError: module 'pyastar' has no attribute 'astar_path'`

**Comment by SquarerFive** [comment]
Will need to install the binary for pyastar:
```sh
conda activate battlefield
python -m pip install pyastar-0.0.1-cp38-cp38-win_amd64.whl
```
[pyastar-0.0.1-cp38-cp38-win_amd64.zip](https://github.com/SquarerFive/bf3-bots/files/5942427/pyastar-0.0.1-cp38-cp38-win_amd64.zip)

**Comment by LoveMiku233** [comment]
Thanks
