### ISSUE TITLE
AIServer Packaging

### ISSUE THREAD

**Issue by SquarerFive** [SquarerFive/bf3-bots#18]
Packaging with all dependencies now works. Need to test on my other PC.

noreload parameter must be passed otherwise it will not start
```
./dist\AIHelper/AIHelper.exe runserver --noreload
```

**Comment by EP1CN3SS2** [comment]
When inputting "./dist/AIHelper/AIHelper.exe runserver --noreload" into powershell, nothing happens, it doesn't recognize the input. I can't find an exe of AlHelper anywhere, I have both zips from the releases tab downloaded and extracted. I'm trying to follow the installation steps exactly, but they are not specific enough for a beginner like myself.

**Comment by SquarerFive** [comment]
Ah, I will post the binaries for it in the 'releases' section on the 0.0.4 release.

**Comment by EP1CN3SS2** [comment]
Awesome thanks!

**Comment by SquarerFive** [comment]
Released binaries:
https://github.com/SquarerFive/bf3-bots/releases/tag/0.0.4

Tested those binaries on my other PC which seems to work fine, with no dependency problems.
